apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-gpu-pod
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-gpu-pod
      app.kubernetes.io/name: qwen-hpa-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-06-23T19:51:21+08:00"
        scope.scheduling.crane.io: housekeeper
      creationTimestamp: null
      labels:
        app: test-gpu-pod
        app.kubernetes.io/name: qwen-hpa-demo
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: fake-container
        resources:
          requests:
            nvidia.com/gpu: "1"
          limits:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kwok.x-k8s.io/node
        operator: Exists
      - effect: NoSchedule
        key: tke.cloud.tencent.com/eni-ip-unavailable
        operator: Exists
