image: "ccr.ccs.tencentyun.com/tke-ai-playbook/dynamo:v0.3.0-raycluster"
rayVersion: "2.46.0"

modelVolume:
  hostPath:
    path: /data0

configs: |
  Common:
    model: /data/models/deepseek-ai/DeepSeek-R1
    block-size: 128
    max-model-len: 16384
    kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
    tensor-parallel-size: 16
    max-num-batched-tokens: 16384

  Frontend:
    served_model_name: deepseek-ai/DeepSeek-R1
    endpoint: dynamo.Processor.chat/completions
    port: 8000

  Processor:
    router: round-robin
    common-configs: [model, block-size]

  VllmWorker:
    remote-prefill: true
    conditional-disagg: false
    compilation-config: '{"cudagraph_capture_sizes": [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64]}'
    ServiceArgs:
      workers: 1
      resources:
        gpu: '16'
    common-configs: [model, block-size, max-model-len, kv-transfer-config, tensor-parallel-size]

  PrefillWorker:
    enforce-eager: true
    ServiceArgs:
      workers: 1
      resources:
        gpu: '16'
    common-configs: [model, block-size, max-model-len, kv-transfer-config, tensor-parallel-size, max-num-batched-tokens, enforce-eager]

graphs: |
  from components.frontend import Frontend
  from components.processor import Processor
  from components.worker import VllmWorker

  Frontend.link(Processor).link(VllmWorker)
  
remotePrefill: true

nats:
  enable: true
  config:
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: /data
        pvc:
          enabled: true
          size: 10Gi

etcd:
  enable: true
  replicaCount: 1
  # Explicitly remove authentication
  auth:
    rbac:
      create: false

  readinessProbe:
    enabled: false

  livenessProbe:
    enabled: false

  persistence:
    size: 20Gi
    resources:
    requests:
      cpu: 10
      memory: 20Gi
    limits:
      cpu: 10
      memory: 20Gi
