apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-creator
subjects:
  - kind: ServiceAccount
    name: job-creator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-creator