{{- with .Values.server.decode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" $ }}-decode
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
    component: decode
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" $ | nindent 6 }}
      component: decode
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" $ | nindent 8 }}
        component: decode
    spec:
      {{- if .hostNetwork.enabled }}
      hostNetwork: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 0
      {{- end }}
      enableServiceLinks: false
      containers:
      - name: server
        image: {{ .image }}
        imagePullPolicy: {{ .imagePullPolicy }}
        {{- if .hostNetwork.enabled }}
        securityContext:
          privileged: true
        {{- end }}
        command: ["bash", "-c"]
        args:
        - |
          cd /workspace/examples/llm;
          dynamo serve components.worker:VllmWorker -f ./configs/config.yaml;
        resources:
          {{- toYaml .resources | nindent 10 }}
        env:
        - name: NATS_SERVER
          value: "{{ include "nats.server" $ }}"
        - name: ETCD_ENDPOINTS
          value: "{{ include "etcd.endpoints" $ }}"
        {{- if .env }}
        {{- toYaml .env | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: config
          mountPath: /workspace/examples/llm/configs
        {{- if $.Values.model.pvc.enabled }}
        - name: model
          mountPath: /data/model
          subPath: {{ $.Values.model.pvc.path }}
        {{- else if $.Values.model.local.enabled }}
        - name: model
          mountPath: /data/model
        {{- end }}
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 15Gi
      - name: config
        configMap:
          name: {{ include "helm.fullname" $ }}-decode-config
      {{- if $.Values.model.pvc.enabled }}
      - name: model
        persistentVolumeClaim:
          claimName: {{ $.Values.model.pvc.name }}
      {{- else if $.Values.model.local.enabled }}
      - name: model
        hostPath:
           path: {{ $.Values.model.local.path }}
      {{- end }}
{{- end }}