{{- if .Values.llmbench.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm.fullname" . }}-llmbench
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    component: llmbench
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: llmbench
        image: ccr.ccs.tencentyun.com/tke-ai-playbook/llmbench:nightly
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
        - |
          until curl -sf http://${HOST}:8000/health; do sleep 10; done;
          sleep 60;
          bash bench.sh
          ISL=2500 OSL=100 bash benchmark_serving_concurrency.sh
          tail -f /dev/null
        env:
        - name: HOST
          value: {{ include "helm.fullname" . }}-{{ .Values.llmbench.service }}
        - name: MODEL
          value: {{ .Values.llmbench.model }}
        - name: TOKENIZER
          value: /data/models/{{ .Values.llmbench.model }}
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - mountPath: /data/models
          name: models
      enableServiceLinks: false
      volumes:
      - name: models
        {{- toYaml .Values.modelVolume | nindent 8 }}
{{- end }}