{{- range .Values.deployments }}
---
apiVersion: v1
data:
  configs.yaml: |
{{ .configs | nindent 4 }}
{{- range .additionalConfigs }}
{{- .name | nindent 2 }}: |
{{- .content | nindent 4 }}
{{- end }}
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" $ }}-{{ .name }}-configs
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
    component: {{ .name }}
---
apiVersion: v1
data:
  graphs.py: |
{{ .graphs | nindent 4 }}
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" $ }}-{{ .name }}-graphs
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
    component: {{ .name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" $ }}-{{ .name }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
    component: {{ .name }}
spec:
  replicas: {{ .replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" $ | nindent 6 }}
      component: {{ .name }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" $ | nindent 8 }}
        component: {{ .name }}
    spec:
      hostNetwork: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 0
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        imagePullPolicy: {{ .imagePullPolicy }}
        securityContext:
          privileged: true
          capabilities:
            add: ["IPC_LOCK"]
        command: ["bash", "-c"]
        args:
        - |
          cd {{ .workspace }} && dynamo serve graphs.graphs:{{ .component }} -f ./configs/configs.yaml
        resources:
          {{ toYaml .resources | nindent 10 }}
        env:
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: "spawn"
        - name: NATS_SERVER
          value: "{{ include "nats.server" $ }}"
        - name: ETCD_ENDPOINTS
          value: "{{ include "etcd.endpoints" $ }}"
        - name: NCCL_IB_GID_INDEX
          value: "3"
        - name: NCCL_IB_HCA
          value: "mlx5"
        - name: NCCL_SOCKET_IFNAME
          value: "eth0"
        - name: GLOO_SOCKET_IFNAME
          value: "eth0"
        {{- if .debug }}
        - name: DYN_LOG
          value: "debug"
        - name: NCCL_DEBUG
          value: "INFO"
        {{- end }}
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: models
          mountPath: /data/models
        - name: configs
          mountPath: {{ .workspace }}/configs
        - name: graphs
          mountPath: {{ .workspace }}/graphs
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 15Gi
      - name: configs
        configMap:
          name: {{ include "helm.fullname" $ }}-{{ .name }}-configs
      - name: graphs
        configMap:
          name: {{ include "helm.fullname" $ }}-{{ .name }}-graphs
      - name: models
        {{- toYaml $.Values.modelVolume | nindent 8 }}
{{- if .service.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" $ }}-{{ .name }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
    component: {{ .name }}
spec:
  ports:
  - name: http
    port: {{ .service.port }}
    protocol: TCP
    targetPort: {{ default .service.port .service.targetPort }}
  selector:
    {{- include "helm.selectorLabels" $ | nindent 4 }}
    component: {{ .name }}
  type: ClusterIP
{{- end }}
{{- end }}
