{{- if .Values.vllm.enable }}
{{- with .Values.vllm }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" $ }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
      - name: vllm
        image: {{ .image }}
        imagePullPolicy: {{ .imagePullPolicy }}
        command: ["bash", "-c"]
        args:
        - |
{{ .cmd | nindent 10 }}
        resources:
          {{ toYaml .resources | nindent 10 }}
        env:
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: "spawn"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: models
          mountPath: /data/models
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 15Gi
      - name: models
        {{- toYaml $.Values.modelVolume | nindent 8 }}
{{- if .service.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" $ }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .service.port }}
    protocol: TCP
    targetPort: {{ default .service.port .service.targetPort }}
  selector:
    {{- include "helm.selectorLabels" $ | nindent 4 }}
  type: {{ .service.type }}
{{- end }}
{{- end }}
{{- end }}