{
 "title": "Horizontal Pod Autoscaler (HPA)",
 "description": "Kubernetes (k8s) Horizontal Pod Autoscaler (HPA)",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ns",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info, namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation{namespace=\"$ns\"},deployment)"
    }
   },
   {
    "name": "hpa",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info{namespace=~\"$ns\", scaletargetref_kind=\"Deployment\", scaletargetref_name=\"$deployment\"},horizontalpodautoscaler)"
    }
   },
   { "name": "model_name", "query": { "query": "label_values(model_name)" } }
  ]
 },
 "panels": [
  { "title": "$hpa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hpa" },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Replicas ($hpa)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "current"
    },
    {
     "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"$ns\",pod=~\"$deployment-.*\",endpoint=\"http\",phase=~\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (condition) (kube_pod_status_ready{namespace=\"$ns\", pod=~\"$deployment-.*\",endpoint=\"http\",condition=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target Metric ($hpa)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "target ({{metric_name}}: {{metric_target_type}})"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}\n  and on(metric_name, metric_target_type)\n    kube_horizontalpodautoscaler_spec_target_metric{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "current ({{metric_name}}: {{metric_target_type}})"
    }
   ]
  }
 ]
}